Module SelectLang

    Public EnableEn, EnableCn As Boolean
    Dim LangSelect As String
    Public LoStr(50) As String

    Sub Main()
        Console.WriteLine()
        Console.WriteLine("         _              _            _              _        _                _      ")
        Console.WriteLine("        /\ \           /\ \         /\ \     _     /\ \    /\ \             /\ \     ")
        Console.WriteLine("       /  \ \         /  \ \       /  \ \   /\_\   \ \ \  /  \ \           /  \ \    ")
        Console.WriteLine("      / /\ \_\       / /\ \ \     / /\ \ \_/ / /   /\ \_\/ /\ \ \         / /\ \ \   ")
        Console.WriteLine("     / / /\/_/      / / /\ \_\   / / /\ \___/ /   / /\/_/\/_/\ \ \       / / /\ \ \  ")
        Console.WriteLine("    / / / ______   / /_/_ \/_/  / / /  \/____/   / / /       / / /      / / /  \ \_\ ")
        Console.WriteLine("   / / / /\_____\ / /____/\    / / /    / / /   / / /       / / /      / / /    \/_/ ")
        Console.WriteLine("  / / /  \/____ // /\____\/   / / /    / / /   / / /       / / /  _   / / /          ")
        Console.WriteLine(" / / /_____/ / // / /______  / / /    / / /___/ / /__     / / /_/\_\ / / /________   ")
        Console.WriteLine("/ / /______\/ // / /_______\/ / /    / / //\__\/_/___\   / /_____/ // / /_________\  ")
        Console.WriteLine("\/___________/ \/__________/\/_/     \/_/ \/_________/   \________/ \/____________/  ")
        'http://patorjk.com Impossible
        Console.WriteLine()

        While LangSelect <> "1" And LangSelect <> "2"
            Console.WriteLine()
            Console.WriteLine("Select Language 选择语言:")
            Console.WriteLine()
            Console.WriteLine("1) English")
            Console.WriteLine("2) 简体中文")
            Console.WriteLine()
            Console.Write("Your Choice 你的选择: ")
            LangSelect = Console.ReadLine()
        End While
        Console.WriteLine()
        If LangSelect = "1" Then EnableEn = True
        If LangSelect = "2" Then EnableCn = True
        Localization()
    End Sub

    Sub Localization()

        If EnableCn = True Then

            LoStr(0) = ("请输入文件路径 (将文件拖放至窗口内) : ")
            LoStr(1) = ("不支持 AML 文件! 请重新输入!")
            LoStr(2) = ("未知文件! 请重新输入!")
            LoStr(3) = ("文件不存在, 请重新输入!")
            LoStr(4) = ("路径中存在非法字符, 请重新输入!")
            LoStr(5) = ("输入您的 I2C 设备名")
            LoStr(6) = ("请正确输入您的设备名 (如: " & Chr(34) & "TPD" & Chr(34) & ")!")
            LoStr(7) = ("未知错误, 请在 GitHub 上提交你的文件和问题反馈")
            LoStr(8) = ("即将退出")
            LoStr(9) = '("USTP 存在于 DSDT 的第 " & line + 1 & " 行")
            LoStr(10) = '("SSCN 存在于 DSDT 的第 " & line + 1 & " 行")
            LoStr(11) = '("FMCN 存在于 DSDT 的第 " & line + 1 & " 行")
            LoStr(12) = ("DSDT 中不存在这个设备")
            LoStr(13) = '("原生 Gpioint 存在于 " & TPAD & " 中的第 " & i + 1 & " 行")
            LoStr(14) = '("原生 APIC 存在于 " & TPAD & " 中的第 " & i + 1 & " 行")
            LoStr(15) = '("I2C 从地址 存在于 " & TPAD & " 中的第 " & i + 1 & " 行")
            LoStr(16) = ("这不是一个 I2C 设备!")
            LoStr(17) = ("选择你的 CPU 架构:")
            LoStr(18) = ("1) Sunrise Point:  SKL, KBL, KBL-R (6代至八代低压)")
            LoStr(19) = ("2) Cannon Lake (Point)-H:  CFL-H (875H, 83H) (八代标压)")
            LoStr(20) = ("3) Cannon Lake (Point)-LP: CFL-R (8565U, 8265U) (八代低压 Whiskey Lake)")
            LoStr(21) = ("您的选择: ")
            LoStr(22) = ("选择您需要的补丁模式")
            LoStr(23) = ("1) 中断 (APIC 或 GPIO)")
            LoStr(24) = ("2) 轮询 (会在可能时回到 APIC 中断)")
            LoStr(25) = ("3) * 屏蔽一条 I2C 总线")
            LoStr(26) = ("您要屏蔽哪条 I2C 总线?")
            LoStr(27) = ("未知操作, 正在退出")
            LoStr(28) = ("APIC Pin 值 < 2F, 支持原生 APIC 中断")
            LoStr(29) = ("提取 APIC Pin 失败, Pin 值由系统启动时填充。请以十六进制输入您的 APIC Pin")
            LoStr(30) = ("APIC Pin 超出范围!")
            LoStr(31) = ("1) 重新输入")
            LoStr(32) = ("2) 退出")
            LoStr(33) = ("APIC Pin 值 < 2F, 支持原生 APIC 中断")
            LoStr(34) = ("原生 GpioInt 不存在, 已自动生成")
            LoStr(35) = ("APIC Pin 大小未知, 可能是 APIC 中断或轮询")
            LoStr(36) = ("原生 APIC 不存在，提取 APIC Pin 失败。请以十六进制输入您的 APIC Pin")
            LoStr(37) = ("APIC Pin 超出范围!")
            LoStr(38) = ("APIC Pin 值 < 2F, 支持原生 APIC 中断，将不会生成 _CRS 补丁")
            LoStr(39) = ("未知情况，请在 GitHub 上提交你的文件和问题反馈")
            LoStr(40) = ("错误! 没有 _CRS 补丁被应用!")
            LoStr(41) = ("APIC Pin 值 < 2F, 支持原生 APIC 中断, GPIO 生成已取消")
            LoStr(42) = ("查找 _CRS:          5F 43 52 53")
            LoStr(43) = ("替换 XCRS:          58 43 52 53")
            LoStr(44) = ("查找 _STA:          5F 53 54 41")
            LoStr(45) = ("替换 XSTA:          58 53 54 41")
            LoStr(46) = ("查找 USTP:          55 53 54 5 8")
            LoStr(47) = ("替换 XSTP:          58 53 54 5 8")
            LoStr(48) = ("生成完成!")
            LoStr(49) = ("输入 " & Chr(34) & "Exit" & Chr(34) & " 以退出")

        ElseIf EnableEn = True Then

            LoStr(0) = ("File Path (Drag and Drop the dsl file into the Form) : ")
            LoStr(1) = ("AML files aren't supported! Please input again!")
            LoStr(2) = ("Unknown File! Please input again!")
            LoStr(3) = ("File doesn't exist, please input again!")
            LoStr(4) = ("Illegal Characters exists, please input again!")
            LoStr(5) = ("Input your I2C Device's name")
            LoStr(6) = ("Please Input your device name correctly (e.g. " & Chr(34) & "TPD0" & Chr(34) & ")!")
            LoStr(7) = ("Unknown error, please open an issue and provide your files")
            LoStr(8) = ("Exiting")
            LoStr(9) = '("Found for USTP in DSDT at line " & line + 1)
            LoStr(10) = '("Found for SSCN in DSDT at line " & line + 1)
            LoStr(11) = '("Found for FMCN in DSDT at line " & line + 1)
            LoStr(12) = ("This is not a Device that exists in the DSDT")
            LoStr(13) = '("Native GpioInt Found in " & TPAD & " at line " & i + 1)
            LoStr(14) = '("Native APIC Found in " & TPAD & " at line " & i + 1)
            LoStr(15) = '("Slave Address Found in " & TPAD & " at line " & i + 1)
            LoStr(16) = ("This is not a I2C Device!")
            LoStr(17) = ("Select your CPU architecture:")
            LoStr(18) = ("1) Sunrise Point:  SKL, KBL, KBL-R")
            LoStr(19) = ("2) Cannon Lake (Point)-H:  CFL-H (8750H, 8300H)")
            LoStr(20) = ("3) Cannon Lake (Point)-LP: CFL-R (8565U, 8265U)")
            LoStr(21) = ("Your Choice: ")
            LoStr(22) = ("Choose the mode you'd like to patch")
            LoStr(23) = ("1) Interrupt (APIC or GPIO)")
            LoStr(24) = ("2) Polling (Will be set back to APIC if supported)")
            LoStr(25) = ("3) * Block an I2C Bus")
            LoStr(26) = ("Which I2C Bus you'd like to block?")
            LoStr(27) = ("Unknown Behaviour, Exiting")
            LoStr(28) = ("APIC Pin value < 2F, Native APIC Supported, using instead")
            LoStr(29) = ("Failed to extract APIC Pin, filled by system start up. Please input your APIC Pin in Hex")
            LoStr(30) = ("APIC Pin out of range!")
            LoStr(31) = ("1) Input again")
            LoStr(32) = ("2) Exit")
            LoStr(33) = ("APIC Pin value < 2F, Native APIC Supported, using instead")
            LoStr(34) = ("No native GpioInt found, Generating instead")
            LoStr(35) = ("APIC Pin size uncertain, could be either APIC or polling")
            LoStr(36) = ("No native APIC found, failed to extract APIC Pin. Please input your APIC Pin in Hex")
            LoStr(37) = ("APIC Pin out of range!")
            LoStr(38) = ("APIC Pin value < 2F, Native APIC Supported, No _CRS Patch required")
            LoStr(39) = ("Undefined Situation")
            LoStr(40) = ("Error! No _CRS Patch Applied!")
            LoStr(41) = ("APIC Pin value < 2F, Native APIC Supported, Generation Cancelled")
            LoStr(42) = ("Find _CRS:          5F 43 52 53")
            LoStr(43) = ("Replace XCRS:       58 43 52 53")
            LoStr(44) = ("Find _STA:          5F 53 54 41")
            LoStr(45) = ("Replace XSTA:       58 53 54 41")
            LoStr(46) = ("Find USTP:          55 53 54 50 08")
            LoStr(47) = ("Replace XSTP:       58 53 54 50 08")
            LoStr(48) = ("Enjoy!")
            LoStr(49) = ("Type in " & Chr(34) & "Exit" & Chr(34) & " to exit")

        End If
        Input()
    End Sub
End Module
